Print repeated Problem for Problem page
googleinterns/step58-2020 pull request #43
Opened 2020-07-16 22:31 UTC by lalaAdasia00

2020-07-16 23:04 UTC, nicholashusin requested changes

2020-07-16 23:04 UTC, Nicholas2750 commented on problems/printRepeated.yaml
> +    }
Missing `return` statement

2020-07-17 13:24 UTC, ifeomi commented on problems/printRepeated.yaml
> +  /* Hint- Helper fucntion may be used */
```suggestion
  /* Hint- Helper function may be used */
```

2020-07-17 13:24 UTC, ifeomi commented on problems/printRepeated.yaml
> +  printRepeated('hello', 4, 3) =
should we change the name to generateRepeated?

2020-07-17 13:24 UTC, ifeomi commented on problems/printRepeated.yaml
> +  where each string is repeated a times.
should rephrase since they aren't printing

2020-07-20 20:54 UTC, chronologos approved these changes

2020-07-20 21:06 UTC, nicholashusin approved these changes

2020-07-20 21:09 UTC, merged